services:
  my-sql:
    image: mysql:latest
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_service
      MYSQL_USER: root
    ports:
      - "3308:3306"
    volumes:
      - dbstore:/var/lib/mysql
    networks:
      - car-service-network
    restart: always

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - my-sql
    networks:
      - car-service-network
#    restart: always

  frontend:
      build: ./frontend
      ports:
        - "4200:80"
      links:
        - backend
      networks:
        - car-service-network

volumes:
  dbstore:

networks:
  car-service-network: